# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/bep/inflect";
    fetch = {
      type = "git";
      url = "https://github.com/bep/inflect";
      rev = "b896c45f5af983b1f416bdf3bb89c4f1f0926f69";
      sha256 = "0drv6in94n7lmap4ajvgqlvdcbpn8alinfdzywzpihvzbx21b3h3";
    };
  }
  {
    goPackagePath = "github.com/gotk3/gotk3";
    fetch = {
      type = "git";
      url = "https://github.com/gotk3/gotk3";
      rev = "289cfb6dbf32de11dd2a392e86de4a144ac6be48";
      sha256 = "1i91gyix0ij944x8j1pz2j6kv85h98x348qf4h8klj1n8r048w2y";
    };
  }
  {
    goPackagePath = "github.com/orivej/e";
    fetch = {
      type = "git";
      url = "git@github.com:orivej/e.git";
      rev = "ac3492690fda471c5eab817efd86badf5c3ac158";
      sha256 = "11jizr28kfkr6zscjxg95pqi6cjp08aqnhs41sdhc98nww78ilkr";
    };
  }
]
